# Generated by Django 3.2.8 on 2021-10-11 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_group',
            name='participant_one',
        ),
        migrations.RemoveField(
            model_name='chat_group',
            name='participant_two',
        ),
        migrations.AddField(
            model_name='chat_group',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
